In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({
    'Population': [35.467, 63.951, 80.94 , 60.665, 127.061, 64.511, 318.523],
    'GDP': [
        1785387,
        2833687,
        3874437,
        2167744,
        4602367,
        2950039,
        17348075
    ],
    'Surface Area': [
        9984670,
        640679,
        357114,
        301336,
        377930,
        242495,
        9525067
    ],
    'HDI': [
        0.913,
        0.888,
        0.916,
        0.873,
        0.891,
        0.907,
        0.915
    ],
    'Continent': [
        'America',
        'Europe',
        'Europe',
        'Europe',
        'Asia',
        'Europe',
        'America'
    ]
}, columns=['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'])

In [3]:
df

   Population       GDP  Surface Area    HDI Continent
0      35.467   1785387       9984670  0.913   America
1      63.951   2833687        640679  0.888    Europe
2      80.940   3874437        357114  0.916    Europe
3      60.665   2167744        301336  0.873    Europe
4     127.061   4602367        377930  0.891      Asia
5      64.511   2950039        242495  0.907    Europe
6     318.523  17348075       9525067  0.915   America

In [6]:
df.index = [
    'Canada',
    'France', 
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'USA'
]

In [10]:
df.index

Index(['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom',
       'USA'],
      dtype='object')

In [9]:
df.info

<bound method DataFrame.info of                 Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
USA                318.523  17348075       9525067  0.915   America>

In [7]:
df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
USA                318.523  17348075       9525067  0.915   America

In [11]:
df.size

35

In [12]:
df.shape

(7, 5)

In [13]:
df.describe()

       Population           GDP  Surface Area       HDI
count    7.000000  7.000000e+00  7.000000e+00  7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429
std     97.249970  5.494020e+06  4.576187e+06  0.016592
min     35.467000  1.785387e+06  2.424950e+05  0.873000
25%     62.308000  2.500716e+06  3.292250e+05  0.889500
50%     64.511000  2.950039e+06  3.779300e+05  0.907000
75%    104.000500  4.238402e+06  5.082873e+06  0.914000
max    318.523000  1.734808e+07  9.984670e+06  0.916000

In [15]:
df.dtypes

Population      float64
GDP               int64
Surface Area      int64
HDI             float64
Continent        object
dtype: object

In [16]:
df.loc['Canada']

Population       35.467
GDP             1785387
Surface Area    9984670
HDI               0.913
Continent       America
Name: Canada, dtype: object

In [17]:
df.iloc[-1]

Population       318.523
GDP             17348075
Surface Area     9525067
HDI                0.915
Continent        America
Name: USA, dtype: object

In [18]:
df['Population']

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
USA               318.523
Name: Population, dtype: float64

In [19]:
df['Population'] > 70

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
USA                True
Name: Population, dtype: bool

In [21]:
df.loc[df['Population'] > 70]

         Population       GDP  Surface Area    HDI Continent
Germany      80.940   3874437        357114  0.916    Europe
Japan       127.061   4602367        377930  0.891      Asia
USA         318.523  17348075       9525067  0.915   America

In [22]:
df.loc[df['Population'] > 70, ['Population', 'GDP']]

         Population       GDP
Germany      80.940   3874437
Japan       127.061   4602367
USA         318.523  17348075

In [23]:
df.drop('Canada')

                Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
USA                318.523  17348075       9525067  0.915   America

In [25]:
langs = pd.Series(['French', 'German', 'Italian'], index=['France', 'Germany', 'Italy'], name='Language')

In [26]:
df['Language'] = langs

In [27]:
df

                Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America      NaN
France              63.951   2833687        640679  0.888    Europe   French
Germany             80.940   3874437        357114  0.916    Europe   German
Italy               60.665   2167744        301336  0.873    Europe  Italian
Japan              127.061   4602367        377930  0.891      Asia      NaN
United Kingdom      64.511   2950039        242495  0.907    Europe      NaN
USA                318.523  17348075       9525067  0.915   America      NaN

In [29]:
df["Language"] = 'English'

In [30]:
df

                Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America  English
France              63.951   2833687        640679  0.888    Europe  English
Germany             80.940   3874437        357114  0.916    Europe  English
Italy               60.665   2167744        301336  0.873    Europe  English
Japan              127.061   4602367        377930  0.891      Asia  English
United Kingdom      64.511   2950039        242495  0.907    Europe  English
USA                318.523  17348075       9525067  0.915   America  English